require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.nvim-tree"
require "user.whichkey"
require "user.lsp"
require "user.treesitter"
require "user.gitsigns"

--require "user.telescope"
